create TABLE CONFERENCES (
    "IDENTIFIANT" NUMBER(10,0) NOT NULL,
    "TITRE" VARCHAR2(200 CHAR) NOT NULL,
	"CATEGORIE" VARCHAR2(20 CHAR) NOT NULL,
	"TYPE" VARCHAR2(20 CHAR),
    "HORODATE_DEBUT" TIMESTAMP NULL,
    "HORODATE_FIN" TIMESTAMP NULL,
    "MATERIEL" VARCHAR2(1000 CHAR),
    "SALLE" VARCHAR2(1000 CHAR),
	PRIMARY KEY (IDENTIFIANT)
);
create sequence CONFERENCE_SEQUENCE increment by 1 start with 100;