insert into PERSONNES("IDENTIFIANT","NOM") values (1,'Johan Martinsson');
insert into PERSONNES("IDENTIFIANT","NOM") values (2,'Bouillier Clément');
insert into PERSONNES("IDENTIFIANT","NOM") values (3,'Florent Pellet');
insert into PERSONNES("IDENTIFIANT","NOM") values (4,'Olivier Leplus');
insert into PERSONNES("IDENTIFIANT","NOM") values (5,'Yohan Lasorsa');
insert into PERSONNES("IDENTIFIANT","NOM") values (6,'Philippe Charrière');
insert into PERSONNES("IDENTIFIANT","NOM") values (7,'Alexandre Gallice');
insert into PERSONNES("IDENTIFIANT","NOM") values (8,'Zineb Bendhiba');
insert into PERSONNES("IDENTIFIANT","NOM") values (9,'Gaëtan Maisse');
insert into PERSONNES("IDENTIFIANT","NOM") values (10,'Thibaud Avenier');
insert into PERSONNES("IDENTIFIANT","NOM") values (11,'Arnaud le Bec');
insert into PERSONNES("IDENTIFIANT","NOM") values (12,'Victor Gallet');
insert into PERSONNES("IDENTIFIANT","NOM") values (13,'Guillaume Lours');
insert into PERSONNES("IDENTIFIANT","NOM") values (14,'Yves Brissaud');
insert into PERSONNES("IDENTIFIANT","NOM") values (15,'Ludovic Piot');
insert into PERSONNES("IDENTIFIANT","NOM") values (16,'Laurent Grangeau');
insert into PERSONNES("IDENTIFIANT","NOM") values (17,'Ljubica Lazarevic');
insert into PERSONNES("IDENTIFIANT","NOM") values (18,'Patrice De Saint Steban');
insert into PERSONNES("IDENTIFIANT","NOM") values (19,'Anthony Le Goas');
insert into PERSONNES("IDENTIFIANT","NOM") values (65,'Noël Macé');
insert into PERSONNES("IDENTIFIANT","NOM") values (66,'Pierre Tibulle');
insert into PERSONNES("IDENTIFIANT","NOM") values (20,'Guillaume Blaquiere');
insert into PERSONNES("IDENTIFIANT","NOM") values (21,'Sylvain Coudert');
insert into PERSONNES("IDENTIFIANT","NOM") values (22,'Sandrine Banas');
insert into PERSONNES("IDENTIFIANT","NOM") values (23,'M4dz');
insert into PERSONNES("IDENTIFIANT","NOM") values (24,'Nicolas Marcq');
insert into PERSONNES("IDENTIFIANT","NOM") values (25,'Antoine Cailly');
insert into PERSONNES("IDENTIFIANT","NOM") values (26,'Adrien Wattez');
insert into PERSONNES("IDENTIFIANT","NOM") values (27,'Stéphane Philippart');
insert into PERSONNES("IDENTIFIANT","NOM") values (28,'Frédéric Cabestre');
insert into PERSONNES("IDENTIFIANT","NOM") values (29,'Adrien Wattez');
insert into PERSONNES("IDENTIFIANT","NOM") values (30,'Gaëlle Acas');
insert into PERSONNES("IDENTIFIANT","NOM") values (31,'Aurélie Vache');
insert into PERSONNES("IDENTIFIANT","NOM") values (32,'Yves Brissaud');
insert into PERSONNES("IDENTIFIANT","NOM") values (33,'Raphaël Verdier');
insert into PERSONNES("IDENTIFIANT","NOM") values (34,'Mathilde Rigabert Lemée');
insert into PERSONNES("IDENTIFIANT","NOM") values (35,'Clement Escoffier');
insert into PERSONNES("IDENTIFIANT","NOM") values (36,'Christophe Tardella');
insert into PERSONNES("IDENTIFIANT","NOM") values (37,'Martin Choraine');
insert into PERSONNES("IDENTIFIANT","NOM") values (38,'Nicolas Delsaux');
insert into PERSONNES("IDENTIFIANT","NOM") values (39,'Estelle Landry');
insert into PERSONNES("IDENTIFIANT","NOM") values (40,'Yvonnick Frin');
insert into PERSONNES("IDENTIFIANT","NOM") values (41,'Julien Topçu');
insert into PERSONNES("IDENTIFIANT","NOM") values (42,'Thomas Breuzard');
insert into PERSONNES("IDENTIFIANT","NOM") values (43,'Nicolas Fränkel');
insert into PERSONNES("IDENTIFIANT","NOM") values (44,'David Pilato');
insert into PERSONNES("IDENTIFIANT","NOM") values (45,'Matthieu V');
insert into PERSONNES("IDENTIFIANT","NOM") values (46,'Grégoire Pineau');
insert into PERSONNES("IDENTIFIANT","NOM") values (47,'Sylvain Dedieu');
insert into PERSONNES("IDENTIFIANT","NOM") values (48,'Mathieu Humbert');
insert into PERSONNES("IDENTIFIANT","NOM") values (49,'Stéphane Teyssier');
insert into PERSONNES("IDENTIFIANT","NOM") values (50,'Benjamin Coenen');
insert into PERSONNES("IDENTIFIANT","NOM") values (51,'Julien Sulpis');
insert into PERSONNES("IDENTIFIANT","NOM") values (52,'Willy Malvault');
insert into PERSONNES("IDENTIFIANT","NOM") values (53,'Philippe Morisseau');
insert into PERSONNES("IDENTIFIANT","NOM") values (54,'Tiffany Souterre');
insert into PERSONNES("IDENTIFIANT","NOM") values (55,'Aurélie Vache');
insert into PERSONNES("IDENTIFIANT","NOM") values (56,'Houssem Belhadj Ahmed');
insert into PERSONNES("IDENTIFIANT","NOM") values (57,'Mickael Jeanroy');
insert into PERSONNES("IDENTIFIANT","NOM") values (58,'Alexandre Touret');
insert into PERSONNES("IDENTIFIANT","NOM") values (59,'Thibaud Courtoison');
insert into PERSONNES("IDENTIFIANT","NOM") values (60,'Adrien Pessu');
insert into PERSONNES("IDENTIFIANT","NOM") values (61,'David Aparicio');
insert into PERSONNES("IDENTIFIANT","NOM") values (62,'Jolyanne Boivin');
insert into PERSONNES("IDENTIFIANT","NOM") values (63,'Antoine Caron');
insert into PERSONNES("IDENTIFIANT","NOM") values (64,'Florent Dubost');

insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 1 ,PARSEDATETIME( '02/02/2022 09:30','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 12:30','dd/MM/yyyy HH:mm'),'Découpe mon monolithe','ATELIER','ARCHITECTURE','Mont Blanc 2');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 2 ,PARSEDATETIME( '02/02/2022 09:30','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 12:30','dd/MM/yyyy HH:mm'),'Développez et déployez votre application web fullstack avec Azure Static Web Apps et GitHub Actions.','ATELIER','CLOUD','Mont Blanc 4');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 3 ,PARSEDATETIME( '02/02/2022 09:30','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 12:30','dd/MM/yyyy HH:mm'),'WASM en douceur avec Go, Rust et Grain','ATELIER','CLOUD','Mont Blanc 3');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 4 ,PARSEDATETIME( '02/02/2022 09:30','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 12:30','dd/MM/yyyy HH:mm'),'Workshop sur l''Intégration à l''ère du cloud avec Camel Quarkus','ATELIER','CLOUD','Mont Blanc 1');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 5 ,PARSEDATETIME( '02/02/2022 09:30','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 12:30','dd/MM/yyyy HH:mm'),'Storybook from Zero to Hero','ATELIER','WEB','Everest');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 6 ,PARSEDATETIME( '02/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 17:00','dd/MM/yyyy HH:mm'),'Workshop Kafka Streams 101','ATELIER','ARCHITECTURE','Mont Blanc 1');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 7 ,PARSEDATETIME( '02/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 17:00','dd/MM/yyyy HH:mm'),'docker compose : le même, mais sans le tiret','ATELIER','CLOUD','Mont Blanc 3');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 8 ,PARSEDATETIME( '02/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 17:00','dd/MM/yyyy HH:mm'),'GitOps, une mise en situation un peu réaliste sur Kubernetes avec FluxCD','ATELIER','CLOUD','Mont Blanc 4');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 9 ,PARSEDATETIME( '02/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 17:00','dd/MM/yyyy HH:mm'),'Using a Design First approach to build a simple book shop application','ATELIER','DISCOVER','Mont Blanc 2');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 10  ,PARSEDATETIME( '02/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '02/02/2022 17:00','dd/MM/yyyy HH:mm'),'Devenir svelte avec Svelte','ATELIER','WEB','Everest');

insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 11 ,PARSEDATETIME( '03/02/2022 09:20','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 10:05','dd/MM/yyyy HH:mm'),' Il était une fois... les navigateurs','KEYNOTE','WEB','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 12 ,PARSEDATETIME( '03/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 11:30','dd/MM/yyyy HH:mm'),'Orchestration de pipeline de données en serverless avec Google Workflow','CONFERENCE','ARCHITECTURE','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 13 ,PARSEDATETIME( '03/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 11:30','dd/MM/yyyy HH:mm'),'Notre cerveau est nul! Quelques biais cognitifs sous le spectre des métiers du dev...','CONFERENCE','DISCOVER','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 14 ,PARSEDATETIME( '03/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 11:30','dd/MM/yyyy HH:mm'),'Vous prendrez bien un peu de sucre dans votre java ?','CONFERENCE','LANGUAGE','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 15 ,PARSEDATETIME( '03/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 11:30','dd/MM/yyyy HH:mm'),'The Eternal Sunshine of the Zero Build Pipeline','CONFERENCE','WEB','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 16 ,PARSEDATETIME( '03/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 12:30','dd/MM/yyyy HH:mm'),'Automation as a service avec la stack Ansible/Tower/Squest','CONFERENCE','CLOUD','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 17 ,PARSEDATETIME( '03/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 12:30','dd/MM/yyyy HH:mm'),'Identité numérique décentralisée et droit d''être soi : protéger son intégrité sur Internet','CONFERENCE','DISCOVER','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 18 ,PARSEDATETIME( '03/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 12:30','dd/MM/yyyy HH:mm'),'L’Open Source au secours du développeur (et de l’architecte) ?','CONFERENCE','DISCOVER','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 19 ,PARSEDATETIME( '03/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 12:30','dd/MM/yyyy HH:mm'),'Les fonctions (récursives) décortiquées','CONFERENCE','LANGUAGE','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 20 ,PARSEDATETIME( '03/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 14:45','dd/MM/yyyy HH:mm'),'Soyez réactif avec RSocket (Reactive Socket)','CONFERENCE','ARCHITECTURE','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 21 ,PARSEDATETIME( '03/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 14:45','dd/MM/yyyy HH:mm'),'Créer & distribuer un plugin pour Kubernetes en quelques minutes ? Easy ! ??','CONFERENCE','CLOUD','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 22 ,PARSEDATETIME( '03/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 14:45','dd/MM/yyyy HH:mm'),'Et si les micro-services n''avaient rien à voir avec la technique ?','CONFERENCE','DISCOVER','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 23 ,PARSEDATETIME( '03/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 14:45','dd/MM/yyyy HH:mm'),'Les tests unitaires Javascript, vers l''infini et au-delà','CONFERENCE','LANGUAGE','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 24 ,PARSEDATETIME( '03/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 15:45','dd/MM/yyyy HH:mm'),'Migrer une « vraie application du monde réel » vers Quarkus. Comment ? Mais surtout pourquoi ?','CONFERENCE','CLOUD','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 25 ,PARSEDATETIME( '03/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 15:45','dd/MM/yyyy HH:mm'),'Web-Types : des types pour vos templates HTML !','CONFERENCE','DISCOVER','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 26 ,PARSEDATETIME( '03/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 15:45','dd/MM/yyyy HH:mm'),'REX Mutation Testing, après un an de mise en place chez un client','CONFERENCE','LANGUAGE','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 27 ,PARSEDATETIME( '03/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 15:45','dd/MM/yyyy HH:mm'),'La Clean Architecture dans le web','CONFERENCE','WEB','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 28 ,PARSEDATETIME( '03/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 16:45','dd/MM/yyyy HH:mm'),'C4 et au-delà : documenter une architecture agilement','CONFERENCE','ARCHITECTURE','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 29 ,PARSEDATETIME( '03/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 16:45','dd/MM/yyyy HH:mm'),'Notre recette de l’équipe parfaite','CONFERENCE','DISCOVER','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 30 ,PARSEDATETIME( '03/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '03/02/2022 16:45','dd/MM/yyyy HH:mm'),'REST next level : Ecrire des APIs web orientées métier','CONFERENCE','LANGUAGE','Makalu');
                  
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 31 ,PARSEDATETIME( '04/02/2022 09:20','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 10:05','dd/MM/yyyy HH:mm'),'La PermaEntreprise','KEYNOTE','DISCOVER','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 32 ,PARSEDATETIME( '04/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 11:30','dd/MM/yyyy HH:mm'),'Ajoutez une vraie recherche à votre application legacy sans vous prendre la tête','CONFERENCE','ARCHITECTURE','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 33 ,PARSEDATETIME( '04/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 11:30','dd/MM/yyyy HH:mm'),'Qu''est-ce que l''InnerSource ? Comment ça se met en place et pourquoi ça va améliorer votre IT ... mais pas que ?','CONFERENCE','CLOUD','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 34 ,PARSEDATETIME( '04/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 11:30','dd/MM/yyyy HH:mm'),'Redis, ce n''est pas que pour le cache','CONFERENCE','LANGUAGE','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 35 ,PARSEDATETIME( '04/02/2022 10:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 11:30','dd/MM/yyyy HH:mm'),'Construisons ensemble une application Micro-Frontend multi-frameworks avec Webpack 5 Module Federation','CONFERENCE','WEB','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 36 ,PARSEDATETIME( '04/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 12:30','dd/MM/yyyy HH:mm'),'Les bonnes pratiques OAuth2/OIDC conjuguées au présent, passé simple et futur','CONFERENCE','ARCHITECTURE','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 37 ,PARSEDATETIME( '04/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 12:30','dd/MM/yyyy HH:mm'),'InfraAsCode et multicloud à la sauce Kubernetes avec Crossplane','CONFERENCE','CLOUD','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 38 ,PARSEDATETIME( '04/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 12:30','dd/MM/yyyy HH:mm'),'WebAssembly n''est pas qu''une affaire de frontend','CONFERENCE','DISCOVER','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 39 ,PARSEDATETIME( '04/02/2022 11:45','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 12:30','dd/MM/yyyy HH:mm'),'La 3D sur le web : trucs et astuces pour un effet "wahou" garanti !','CONFERENCE','WEB','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 40 ,PARSEDATETIME( '04/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 14:45','dd/MM/yyyy HH:mm'),'L''histoire de SRP, le protocole d''authentification Zero-Knowledge, contre les pirates à chapeau noir, leurs tables arc-en-ciel et les grufalos.','CONFERENCE','ARCHITECTURE','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 41 ,PARSEDATETIME( '04/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 14:45','dd/MM/yyyy HH:mm'),'Un datahub dans Azure : Retour d''expérience sur les services managés','CONFERENCE','CLOUD','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 42 ,PARSEDATETIME( '04/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 14:45','dd/MM/yyyy HH:mm'),'Y a-t-il un copilote dans mon IDE ?','CONFERENCE','DISCOVER','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 43 ,PARSEDATETIME( '04/02/2022 14:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 14:45','dd/MM/yyyy HH:mm'),'Common tips & mistakes en Go - et comment les résoudre','CONFERENCE','LANGUAGE','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 44 ,PARSEDATETIME( '04/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 15:45','dd/MM/yyyy HH:mm'),'Hack me if you can','CONFERENCE','ARCHITECTURE','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 45 ,PARSEDATETIME( '04/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 15:45','dd/MM/yyyy HH:mm'),'Checklist pour concevoir une application dans le cloud : 10 conseils à l''attention des concepteurs et architectes','CONFERENCE','CLOUD','Kilimanjaro');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 46 ,PARSEDATETIME( '04/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 15:45','dd/MM/yyyy HH:mm'),'Intégration à l''ère du cloud avec Camel Quarkus','CONFERENCE','CLOUD','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 47 ,PARSEDATETIME( '04/02/2022 15:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 15:45','dd/MM/yyyy HH:mm'),'Art & Entropie: Du chaos dans ton frontend','CONFERENCE','WEB','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 48 ,PARSEDATETIME( '04/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 16:45','dd/MM/yyyy HH:mm'),'DevSecOps : de la sécurité dans mon DevOps','CONFERENCE','ARCHITECTURE','Mont Blanc');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 49 ,PARSEDATETIME( '04/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 16:45','dd/MM/yyyy HH:mm'),'Père Castor, raconte nous une histoire (d''OPS)','CONFERENCE','CLOUD','Auditorium');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 50 ,PARSEDATETIME( '04/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 16:45','dd/MM/yyyy HH:mm'),'Entrainer des modèles Deep Learning enproduction avec AWS Sagemaker','CONFERENCE','MACHINE_LEARNING','Makalu');
insert into CONFERENCES("IDENTIFIANT","HORODATE_DEBUT","HORODATE_FIN","TITRE","CATEGORIE","TYPE","SALLE") values ( 51 ,PARSEDATETIME( '04/02/2022 16:00','dd/MM/yyyy HH:mm'),PARSEDATETIME( '04/02/2022 16:00','dd/MM/yyyy HH:mm'),'Comment ne pas jeter son application Frontend tous les deux ans ?','CONFERENCE','WEB','Kilimanjaro');
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	1	,	1	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	1	,	2	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	1	,	3	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	2	,	4	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	2	,	5	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	3	,	6	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	4	,	7	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	4	,	8	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	5	,	9	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	5	,	10	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	6	,	11	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	6	,	12	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	7	,	13	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	7	,	14	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	8	,	15	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	8	,	16	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	9	,	17	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	10	,	18	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	10	,	19	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	11	,	65	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	11	,	66	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	12	,	20	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	13	,	21	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	14	,	22	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	15	,	23	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	16	,	24	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	17	,	25	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	17	,	26	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	18	,	27	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	19	,	28	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	20	,	29	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	21	,	30	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	21	,	31	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	22	,	32	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	23	,	33	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	23	,	34	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	24	,	35	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	25	,	9	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	26	,	36	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	27	,	37	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	28	,	38	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	29	,	39	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	29	,	40	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	30	,	41	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	31	,	42	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	32	,	43	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	32	,	44	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	33	,	6	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	33	,	45	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	34	,	46	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	35	,	47	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	36	,	48	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	37	,	49	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	38	,	50	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	39	,	51	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	40	,	52	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	41	,	53	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	42	,	54	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	43	,	55	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	44	,	56	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	44	,	57	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	45	,	58	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	46	,	7	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	46	,	8	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	47	,	59	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	48	,	60	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	49	,	61	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	50	,	62	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	51	,	63	);
insert into ASSOCIATION_PERSONNE_CONF ("ID_CONFERENCE","ID_PERSONNE") values (	51	,	64	);

